### ISSUE TITLE
crash when opening camera sensitivity

### ISSUE THREAD

**Issue by lukeswitz** [lukeswitz/haven#1]
### Launching CalibrationView from: 
- Settings & monitor inactive: crash
- Settings & monitor active: crash
- Logs ListView > Settings: no crash
- MonitorView: no crash

**Comment by lukeswitz** [comment]
Reopening with some new behaviors based on resources

**Comment by lukeswitz** [comment]
Probably traceable to v4 / v7 support lib conflicts.

**Comment by lukeswitz** [comment]
`11-02 11:48:06.641 7070-7070/org.havenapp.main E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.havenapp.main, PID: 7070
    java.lang.RuntimeException: Unable to resume activity {org.havenapp.main/org.havenapp.main.ui.CameraConfigureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.startPreview()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.startPreview()' on a null object reference
        at com.google.android.cameraview.Camera1.start(Camera1.java:108)
        at com.google.android.cameraview.CameraView.start(CameraView.java:289)
        at org.havenapp.main.sensors.motion.CameraViewHolder.startCamera(CameraViewHolder.java:210)
        at org.havenapp.main.ui.CameraFragment.initCamera(CameraFragment.java:128)
        at org.havenapp.main.ui.CameraFragment.onResume(CameraFragment.java:67)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:6089)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
`

**Comment by lukeswitz** [comment]
XML validation fails across all /res in some form or another schema related:

`Error:(4, 33) cvc-elt.1.a: Cannot find the declaration of element 'manifest'.
Error:(1, 56) s4s-elt-schema-ns: The namespace of element 'x' must be from the schema namespace, 'http://www.w3.org/2001/XMLSchema'.
Error:(1, 56) s4s-elt-invalid: Element 'x' is not a valid element in a schema document.
Error:(1, 56) schema_reference.4: Failed to read schema document 'null', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.`

**Comment by lukeswitz** [comment]
## Noteworthy discoveries: 

- Legacy device cameras don't work with method to gather Prefs for facing & rotation matrix = null camera at camera.start()

### 

- Camera falls back to API 1 and issues from 2017 arise with a null cameraViewHolder. Crash when resuming camera after launching settings activity.

- CameraFacing & rotation is null because some devices don't include that sensor data, a better method is needed (the one used before was fine & worked w/Camera 1&2 APIs) 



- Settings view is broken, text oriented right. This happens when the Prefs XML is not valid, could be the culprit.

- Updated libs causing XML errors, probably not the cause of crash
