### ISSUE TITLE
Crash on camera sensitivity in settings

### ISSUE THREAD

**Issue by lukeswitz** [lukeswitz/haven#24]
Monitor > Settings > Camera sensitivity > Crash

*Logs needed, most likely due to camera reset call on activity.

**Comment by lukeswitz** [comment]
Launching sensitivity settings:
```
07-04 08:09:13.222 2311-2311/org.havenapp.main W/CameraBase: An error occurred while connecting to camera: 1
07-04 08:09:13.222 2311-2311/org.havenapp.main E/Preview: Camera failed to open: Fail to connect to camera service
```
Then, returning to `MonitorActivity`:
```
07-04 08:09:15.624 2311-2311/org.havenapp.main E/ActivityThread: Activity org.havenapp.main.ui.CameraConfigureActivity has leaked ServiceConnection org.havenapp.main.sensors.motion.Preview$1@2b95a326 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity org.havenapp.main.ui.CameraConfigureActivity has leaked ServiceConnection org.havenapp.main.sensors.motion.Preview$1@2b95a326 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1077)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:971)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1774)
        at android.app.ContextImpl.bindService(ContextImpl.java:1757)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
        at org.havenapp.main.sensors.motion.Preview.<init>(Preview.java:127)
        at org.havenapp.main.ui.CameraFragment.initCamera(CameraFragment.java:88)
        at org.havenapp.main.ui.CameraFragment.onResume(CameraFragment.java:60)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
        at android.app.Activity.performResume(Activity.java:6089)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by lukeswitz** [comment]
Build 115 crashlog:
`07-06 08:48:00.266 2893-2893/org.havenapp.main E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.havenapp.main, PID: 2893
    java.lang.RuntimeException: Unable to resume activity {org.havenapp.main/org.havenapp.main.ui.CameraConfigureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.startPreview()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.startPreview()' on a null object reference
        at com.google.android.cameraview.Camera1.start(Camera1.java:113)
        at com.google.android.cameraview.CameraView.start(CameraView.java:282)
        at org.havenapp.main.sensors.motion.CameraViewHolder.startCamera(CameraViewHolder.java:217)
        at org.havenapp.main.ui.CameraFragment.initCamera(CameraFragment.java:118)
        at org.havenapp.main.ui.CameraFragment.onResume(CameraFragment.java:67)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)`

**Comment by lukeswitz** [comment]
Bind handler resolved, camera instance null on resume. New crash from monitor > camera sensitivity > monitor:
`07-06 08:51:14.801 2987-2987/org.havenapp.main E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.havenapp.main, PID: 2987
    java.lang.RuntimeException: Unable to resume activity {org.havenapp.main/org.havenapp.main.MonitorActivity}: java.lang.RuntimeException: startPreview failed
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.RuntimeException: startPreview failed
        at android.hardware.Camera.startPreview(Native Method)
        at com.google.android.cameraview.Camera1.start(Camera1.java:113)
        at com.google.android.cameraview.CameraView.start(CameraView.java:274)
        at org.havenapp.main.sensors.motion.CameraViewHolder.startCamera(CameraViewHolder.java:217)
        at org.havenapp.main.ui.CameraFragment.initCamera(CameraFragment.java:118)
        at org.havenapp.main.ui.CameraFragment.resetCamera(CameraFragment.java:84)
        at org.havenapp.main.ui.CameraFragment.onResume(CameraFragment.java:69)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
        at android.app.Activity.performResume(Activity.java:6089)`

**Comment by lukeswitz** [comment]
Persists in Dev build 2/ also crashes from monitor > sensitivity > monitor directly now if camera can’t find a simple “front” or “back” facing. Attempts to open null camera . Surfacedestroyed is to blame.

**Comment by lukeswitz** [comment]
Updated code still crashes, resets device on 5.1. 2FA and QR linking  put off until stable release candidate.

**Comment by lukeswitz** [comment]
Also documented as issue #321.
